### ISSUE TITLE
プレビューが出ない問題について

### ISSUE THREAD

**Issue by sarashinanikki** [Badlylucky/otoge-thumbnail-generator#1]
ざっと調べた限りを書きます。

結論から言うとAntのUploadを使うのは、今回の用途に少しそぐわないと私は認識しました。
理由は、Uploadコンポーネントは本質的にPOSTリクエストを送るために存在しており、Badlyさんが求めているUI制御の処理はAjax通信を行うXHRライブラリと密に結合しているからです。

AntのUploadコンポーネントは内部で[react-component/Upload](https://github.com/react-component/upload/)を呼び出しており、そこからコールバック関数として`onProgress()`や`onSuccess()`を呼ぶようになっています。
具体的な処理は[request.ts](https://github.com/react-component/upload/blob/master/src/request.ts)に記述されています。

要するにXHRの内部状態とUI描画が同期するような構造になっているため、POSTをしなければうまく動いていないと考えられます。
うまくすればhackもできそうですが、正直他のUIコンポーネントを探した方が筋が良さそうです

**Comment by sarashinanikki** [comment]
あー、そぐわないという程でもないかも......？
要は仮の適当なPOSTをしてしまえばそれでいいので、[mocky](https://designer.mocky.io/)とかを使って適当なエンドポイントをでっちあげて、そこをactionで指定してあげればエラーとかも出ないと思います。多分それが一番早そう

**Comment by Badlylucky** [comment]
https://github.com/Badlylucky/otoge-thumbnail-generator/commit/225770ac736e31a59102a5531854434c91a01f75

これで正常動作するみたいです。描画処理より前にonSuccessイベントを発火していたのが原因のようでした。
